### ISSUE TITLE
runCMAR.java file

### ISSUE THREAD

**Issue by vanderson-rocha** [ianstenbit/arulesCBA#27]
When executing install_LUCS_KDD_CMAR() the following error occurs:

Copy runCMAR.java from  to /home/user/R/x86_64-pc-linux-gnu-library/4.2/arulesCBA/LUCS_KDD/CMAR
Error in install_LUCS_KDD_CMAR() : Copying file failed!
In addition: Warning message:
In file.copy(file.path(src, "runCMAR.java"), path) :
  problem copying /runCMAR.java to /home/vanderson/R/x86_64-pc-linux-gnu-library/4.2/arulesCBA/LUCS_KDD/CMAR/runCMAR.java: No such file or directory

**Comment by vanderson-rocha** [comment]
Same error runs when running install_LUCS_KDD_CPAR()

**Comment by estevaog3** [comment]
Hello, I've removed arules package and when I try to install it again I'm getting the same error.

**Comment by mhahsler** [comment]
It seems like R does not include the file when building the package. You can install a patched version from 

https://mhahsler.r-universe.dev/ui#package:arulesCBA

once it has built arulesCBA version 1.2.3.

Please let me know if this resolves the issue.

Thanks,
Michael

**Comment by vanderson-rocha** [comment]
Hi Michael. I test the solution. It seems it worked but I am getting the below error when calling the CMAR function. Would you know what it is?

Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
        at java.desktop/java.awt.Window.<init>(Window.java:548)
        at java.desktop/java.awt.Frame.<init>(Frame.java:423)
        at java.desktop/java.awt.Frame.<init>(Frame.java:388)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
        at AssocRuleMining.<init>(AssocRuleMining.java:140)
        at TotalSupportTree.<init>(TotalSupportTree.java:80)
        at PartialSupportTree.<init>(PartialSupportTree.java:113)
        at AprioriTFPclass.<init>(AprioriTFPclass.java:123)
        at AprioriTFP_CARgen.<init>(AprioriTFP_CARgen.java:132)
        at AprioriTFP_CMAR.<init>(AprioriTFP_CMAR.java:143)
        at runCMAR.main(runCMAR.java:8)
Error in .LUCS_KDD(formula, trans, method = "CMAR", parameter = paste0("-S",  :
  Error in call: /usr/bin/java  -cp /home/vanderson/R/x86_64-pc-linux-gnu-library/4.2/arulesCBA/LUCS_KDD/CMAR runCMAR -N2 -F/tmp/RtmpmCfiv8/file34e741161a3.num -S10 -C90
Calls: CMAR -> .LUCS_KDD
In addition: Warning message:
In system(exe, intern = TRUE) :
  running command '/usr/bin/java  -cp /home/vanderson/R/x86_64-pc-linux-gnu-library/4.2/arulesCBA/LUCS_KDD/CMAR runCMAR -N2 -F/tmp/RtmpmCfiv8/file34e741161a3.num -S10 -C90' had status 1
Execution halted

**Comment by mhahsler** [comment]
Hi. 

Please run: `system("java -version")`

The LUCS_KDD software needs a Java SDK 1.4.0+ that is not headless. I suppose it is because they also have a GUI packaged in their software. You probably need to install a different Java version.

Let me know if that resolves your issue.

Best,
-Michael

**Comment by vanderson-rocha** [comment]
Now I tested in WINDOWS and the following error appears: Error in system(exe, intern = TRUE) : '“C:\Program' not found

**Comment by vanderson-rocha** [comment]
> system("java -version")
java version "17.0.3.1" 2022-04-22 LTS
Java(TM) SE Runtime Environment (build 17.0.3.1+2-LTS-6)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.3.1+2-LTS-6, mixed mode, sharing)
[1] 0

>

**Comment by mhahsler** [comment]
For your Windows issue, you need a JDK and not just a Runtime Environment that does not include the java compiler `javac`

try: `system("javac -version")`

**Comment by vanderson-rocha** [comment]
> system("javac -version")
javac 17.0.3.1
[1] 0

**Comment by mhahsler** [comment]
I am closing this for now since I cannot replicate the issue.
